# Path where binary protobuf logs will be written
logging.auction_log.path=/opt/data_logs/ssp_module/ssp_bids/ssp_bids_response.log

# Rotation settings for the log producer
logging.auction_log.max_file_size_mb=1000
logging.auction_log.max_backups=50

# Internal performance tuning
logging.auction_log.channel_buffer=10000
logging.auction_log.flush_interval_ms=500


service_log=/opt/service_logs/ssp_module/ssp_bids/ssp_bid_srvc.log
service_log_level=INFO
# WARNING  ERROR
service_log_max_size=100
service_log_max_backups=5
service_log_max_age=30
service_log_compress=true


# Verbose logging for checking
verbose_log=false
verbose_log.path=/opt/service_logs/ssp_module/ssp_bids_verbose/
verbose_log.max_file_size_mb=1000
verbose_log.max_backups=5
# 0.002 ,  1 in 500 request will be logged
verbose_log.sample_rate=0.002  

# Exchange Overhead tuning
exchange.overhead_ms=120

