# Node Monitoring (Centralized Scriping of all Machines)
- targets:
    - 'localhost:9100'
  labels:
    device_name: 'localhost'

- targets:
    - 'ad-1:9100'
  labels:
    device_name: 'ad-1'

- targets:
    - 'ad-2:9100'
  labels:
    device_name: 'ad-2'

- targets:
    - 'ad-3:9100'
  labels:
    device_name: 'ad-3'
