# PM2 Cluster State (Process/Memory Monitoring)
- targets:
    - 'localhost:9209'
  labels:
    device_name: 'localhost'

- targets:
    - 'ad-1:9209'
  labels:
    device_name: 'ad-1'

- targets:
    - 'ad-2:9209'
  labels:
    device_name: 'ad-2'

- targets:
    - 'ad-3:9209'
  labels:
    device_name: 'ad-3'