# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auction_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/auction_log.proto\x12\x03log\"?\n\x03\x41pp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x62undle\x18\x03 \x01(\t\x12\x0e\n\x06\x64omain\x18\x04 \x01(\t\"#\n\x03Web\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\"\xfa\x02\n\x0c\x41uctionEvent\x12\x11\n\ttenant_id\x18\x01 \x01(\r\x12\x16\n\x0essp_partner_id\x18\x02 \x01(\r\x12\x18\n\x10ssp_inventory_id\x18\x03 \x01(\r\x12\x1e\n\x16ssp_partner_auction_id\x18\x04 \x01(\t\x12\x16\n\x0e\x64sp_partner_id\x18\x05 \x01(\r\x12\x18\n\x10\x64sp_inventory_id\x18\x06 \x01(\r\x12\x19\n\x11\x62id_request_price\x18\x07 \x01(\x01\x12\x11\n\tdsp_price\x18\x08 \x01(\x01\x12\x11\n\tssp_price\x18\x0f \x01(\x01\x12\x17\n\x03\x61pp\x18\t \x01(\x0b\x32\x08.log.AppH\x00\x12\x17\n\x03web\x18\n \x01(\x0b\x32\x08.log.WebH\x00\x12\x11\n\ttimestamp\x18\x0b \x01(\x03\x12\x10\n\x08hostname\x18\x0c \x01(\t\x12\x17\n\x0fraw_bid_request\x18\r \x01(\x0c\x12\x18\n\x10raw_dsp_response\x18\x0e \x01(\x0c\x42\x08\n\x06sourceB4Z2github.com/prebid/prebid-server/v3/proto/generatedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auction_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/prebid/prebid-server/v3/proto/generated'
  _APP._serialized_start=32
  _APP._serialized_end=95
  _WEB._serialized_start=97
  _WEB._serialized_end=132
  _AUCTIONEVENT._serialized_start=135
  _AUCTIONEVENT._serialized_end=513
# @@protoc_insertion_point(module_scope)
