{
 "title": "RTB Global Summary",
 "tags": [
  "prebid",
  "rtb",
  "global"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(prebid_rtb_ssp_requests_total, tenant_identifier)"
    }
   },
   {
    "name": "prometheus",
    "label": "Prometheus Instance",
    "query": {
     "query": "label_values(prebid_rtb_ssp_requests_total{tenant_identifier=~\"$tenant\"}, prometheus_identifier)"
    }
   },
   {
    "name": "group_by",
    "label": "Group By",
    "query": "tenant_identifier,prometheus_identifier"
   }
  ]
 },
 "panels": [
  {
   "title": "Global RTB Auctions Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prebid_rtb_auctions_total[$__rate_interval])) by (status)",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Aggregated SSP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prebid_rtb_ssp_requests_total{tenant_identifier=~\"$tenant\", prometheus_identifier=~\"$prometheus\"}[$__rate_interval])) by ($group_by)",
     "legendFormat": "{{$group_by}}"
    }
   ]
  },
  {
   "title": "Aggregated DSP Fan-out Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prebid_rtb_dsp_requests_total{tenant_identifier=~\"$tenant\", prometheus_identifier=~\"$prometheus\"}[$__rate_interval])) by ($group_by)",
     "legendFormat": "{{$group_by}}"
    }
   ]
  }
 ]
}